import logging
import datetime
from pathlib import Path
import json
import math
from typing import Tuple, List
from zoneinfo import ZoneInfo


from appointment import Appointment
from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import InstalledAppFlow
from googleapiclient.discovery import build


class GoogleCalendar:
    SCOPES = ['https://www.googleapis.com/auth/calendar']

    # Google Calendar standard color palette (ID: (R, G, B))
    COLOR_MAP = {
        '1': (121, 134, 203),  # Lavender
        '2': (51, 182, 121),   # Sage
        '3': (142, 36, 170),   # Grape
        '4': (230, 124, 115),  # Flamingo
        '5': (246, 191, 38),   # Banana
        '6': (244, 81, 30),    # Tangerine
        '7': (3, 155, 229),    # Peacock
        '8': (97, 97, 97),     # Graphite
        '9': (63, 81, 181),    # Blueberry
        '10': (11, 128, 67),   # Basil
        '11': (213, 0, 0)      # Tomato
    }

    def __init__(self, calendar_id: str, token_path: Path | str, credentials_path: Path | str):
        self._calendar_id = calendar_id
        self._creds = None

        # Load or refresh credentials
        if Path(token_path).exists():
            self._creds = Credentials.from_authorized_user_file(
                token_path, self.SCOPES)

        if not self._creds or not self._creds.valid:
            if self._creds and self._creds.expired and self._creds.refresh_token:
                self._creds.refresh(Request())
            else:
                flow = InstalledAppFlow.from_client_secrets_file(
                    credentials_path, self.SCOPES)
                self._creds = flow.run_local_server(port=0)

            # Save the credentials for the next run
            with open(token_path, 'w') as token:
                token.write(self._creds.to_json())

        self._service = build('calendar', 'v3', credentials=self._creds)

    @staticmethod
    def _rgb_distance(c1: Tuple[int, int, int], c2: Tuple[int, int, int]) -> float:
        """Calculates Euclidean distance between two RGB colors."""
        return math.sqrt(sum((a - b) ** 2 for a, b in zip(c1, c2)))

    @staticmethod
    def _get_closest_color_id(rgb: Tuple[int, int, int]) -> str:
        """Maps input RGB to the closest Google Calendar color ID."""
        closest_id = '8'  # Default to Graphite
        min_dist = float('inf')

        for color_id, color_val in GoogleCalendar.COLOR_MAP.items():
            dist = GoogleCalendar._rgb_distance(rgb, color_val)
            if dist < min_dist:
                min_dist = dist
                closest_id = color_id
        return closest_id

    def add_appointment(self, appt: Appointment) -> Appointment:
        """Adds the dataclass to the calendar and returns it with the new Google ID."""

        description = " Auto generated by CalendarOCR"

        event_body = {
            'summary': appt.title,
            'description': description,
            'colorId': self._get_closest_color_id(appt.color),
            'start': {
                'dateTime': appt.start_time.isoformat(),
                'timeZone': appt.timezone,  # Adjust if you need local time
            },
            'end': {
                'dateTime': appt.end_time.isoformat(),
                'timeZone': appt.timezone,
            },
        }

        event = self._service.events().insert(
            calendarId=self._calendar_id,
            body=event_body
        ).execute()

        appt.google_event_id = event.get('id')
        return appt

    def get_meetings_in_day(self, target_date: datetime.date, query_timezone: str = "UTC") -> List[Appointment]:
        """
        Returns meetings for a day. 
        query_timezone: Defines which 'day' we are looking at (e.g. 25th in Tokyo vs 25th in NY).
        """

        # Calculate start/end of day relative to the requested timezone
        tz = ZoneInfo(query_timezone)

        # Create midnight at the start of the day in the specific timezone
        start_of_day = datetime.datetime.combine(
            target_date, datetime.time.min, tzinfo=tz)
        # Create midnight at the end of the day
        end_of_day = datetime.datetime.combine(
            target_date, datetime.time.max, tzinfo=tz)

        events_result = self._service.events().list(
            calendarId=self._calendar_id,
            timeMin=start_of_day.isoformat(),
            timeMax=end_of_day.isoformat(),
            singleEvents=True,
            orderBy='startTime'
        ).execute()

        items = events_result.get('items', [])
        appointments = []

        for item in items:
            # Extract Timezone from event, fallback to query_timezone
            event_tz = item['start'].get('timeZone', query_timezone)

            start_str = item['start'].get(
                'dateTime', item['start'].get('date'))
            end_str = item['end'].get('dateTime', item['end'].get('date'))

            # Parse ISO string
            # Note: fromisoformat handles offsets automatically
            start_dt = datetime.datetime.fromisoformat(start_str)
            end_dt = datetime.datetime.fromisoformat(end_str)

            # Extract bbox
            try:
                if 'description' in item:
                    data = json.loads(item['description'])
                    bbox = tuple(data.get('bbox', [0, 0, 0, 0]))
            except json.JSONDecodeError:
                pass

            color_id = item.get('colorId', '8')
            color_rgb = GoogleCalendar.COLOR_MAP.get(color_id, (0, 0, 0))

            appointments.append(Appointment(
                title=item.get('summary', 'No Title'),
                color=color_rgb,
                start_time=start_dt,
                duration=end_dt - start_dt,
                timezone=event_tz,
                google_event_id=item['id']
            ))

        return appointments

    def delete_appointment(self, google_event_id: str):
        """Deletes a specific meeting by ID."""
        try:
            self._service.events().delete(
                calendarId=self._calendar_id,
                eventId=google_event_id
            ).execute()
            logging.getLogger(__name__).info(
                f"Deleted event: {google_event_id}")
        except Exception as e:
            logging.getLogger(__name__).exception(e)

    def delete_all_meetings_in_day(self, target_date: datetime.date):
        """Deletes all meetings found on a given day."""
        appointments = self.get_meetings_in_day(target_date)

        if not appointments:
            logging.getLogger(__name__).info(
                "No appointments found to delete.")
            return

        logging.getLogger(__name__).info(
            f"Deleting {len(appointments)} appointments...")
        # Note: Google offers a batch API if performance becomes an issue for huge numbers
        for appt in appointments:
            if appt.google_event_id:
                self.delete_appointment(appt.google_event_id)
